name: design_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^3.0.0
  flutter_svg: ^1.0.0
  touch_ripple_effect: ^2.2.3
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/AktivGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/AktivGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/AktivGrotesk-Bold.ttf
          weight: 700

  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/fonts/
    - assets/icons/
